### ISSUE TITLE
"Find slime chunks" - Confirmed

### ISSUE THREAD

**Issue by ryanscampbell** [Plethora777/mcpe_viz#18]
I built a fully encased 9 level slime farm from level 40 and below on the slime chunk designated by mcpe_viz, and I was able to collect 50 slimeballs over the course of 5 hours. 

You can probably take off the following disclaimer on your README.md: 

" -- well, maybe... slime chunk finding code not confirmed to work on MCPE yet :)"

**Comment by Plethora777** [comment]
Congrats on the slime farm!  The slime chunks are pretty strange on MCPE.  At least to this point, they are the same for *all* seeds.  (Which is crazy.)  I like the disclaimer because it might save some people a lot of hard work if the devs change the slime chunk calculation :)  I think the disclaimer makes people more likely to confirm slime spawning before doing all the work to create a proper farm.

**Comment by ryanscampbell** [comment]
Sounds good to me:-)
