### ISSUE TITLE
Many *UNKNOWN BLOCK* on map and colours get confused

### ISSUE THREAD

**Issue by phunni** [Plethora777/mcpe_viz#2]
It's possible that this is simply because I've been playing around with a few of the colours in mcpe_viz.xml in order to make certain features stand out more clearly in the maps.

As a result I get *far* more pink blocks identified as *UNKNOWN BLOCK* and mcpe_viz also seems to get confused at times - mistaking one type of block for another.

For example, in the attached file you'll find the data for a world I'm currently using and, near the player's location, there is a bridge build across a small gulley made of cobblestone.  mcpe_viz incorrectly identifies it as snow.

It's possible that the pink *UNKNOWN BLOCK* blocks are simply a result of mcpe_viz not being completed yet?  I'm sure the incorrectly identified blocks are a bug, however.

I couldn't attach the files I used, so I've uploaded a tar.gz (hope that's ok) to dropbox containing my data files and my .cfg and .xml files.

The files is here: https://www.dropbox.com/s/c00p8dupsiukxkv/mcpe_viz.tar.gz?dl=0

**Comment by Plethora777** [comment]
Thanks for the feedback.

You are using a pretty old version of the XML file - and I would guess the code also.  My advice is to download a fresh copy.  I believe you are seeing the issues because the web app relies on colors being *unique* to identify blocks.  The updated code and XML has support for identifying all known block variants too.

You can see if your changes to the XML are causing problems, by doing running jshint on your output .js file.  (See https://www.npmjs.com/package/jshint).  If jshint says that there are duplicate entries, you need to go change those entries in the XML file.

**Comment by Plethora777** [comment]
I'm gonna close this.  Let me know if you have any other issues :)
