### ISSUE TITLE
Geojson is not defined

### ISSUE THREAD

**Issue by Andrewgeochan** [Plethora777/mcpe_viz#38]
Seems it only affects Android MCPE 1.1 (1.0.9 works perfectly)
Fail to copy and paste the whole log file to here, may be it's too large....

When I tried to locate mobs or object, in both IE and Firefox returns the following message.
_________________________________
Vector Load Error
Error: ReferenceError: geojson is not defined

MCPE Viz Hint: If you are loading files from the local filesystem, your browser might not be allowing us to load additional files or examine pixels in maps. Firefox does not have this limitation. See README for more info...
_________________________________

**Comment by Smeo00** [comment]
I'm also experiencing this and in fact have been through all the MCPE 1.1.x.x beta testing builds.
Didn't report it as they were beta rels'.
I'm on Firefox 54.0, checked on IExploder (eugh!).
The world is huge but I've zipped the log, there are a few parsing issues in there also probably due to 1.1.x changes. Hope this helps.
[OldVillageW10.zip](https://github.com/Plethora777/mcpe_viz/files/1095764/OldVillageW10.zip)
Thanks as always for the app!!

**Comment by Andrewgeochan** [comment]
People I found out what was the problem! There is a bug in the "Sign" code, if you delete the "Return", it will work perfectly~
-----------------------From this
{"type":"Feature","geometry":{"type":"Point","coordinates":[717.5,1191.5]},"properties":{"Name":"SignNonBlank","SignNonBlank":{"Text1":"Leatherworker
","Text2":"Butcher
","Text3":"Weaponsmith","Text4":""},"TileEntity":"true","Dimension":"0","Pos":[-259,82,8]}},
-------------------------Into this
{"type":"Feature","geometry":{"type":"Point","coordinates":[717.5,1191.5]},"properties":{"Name":"SignNonBlank","SignNonBlank":{"Text1":"Leatherworker","Text2":"Butcher","Text3":"Weaponsmith","Text4":""},"TileEntity":"true","Dimension":"0","Pos":[-259,82,8]}},

**Comment by Plethora777** [comment]
I think this may be fixed by the new versions lately.  I'm going to close this.  Please feel free to open a new one if it's still a problem.

**Comment by stpsc-rev** [comment]
Well done! you are a star!!
